# Catalog metadata for Plex. Like Jellyfin, no port option in the NixOS
# module -- defaultPort documents Plex's own fixed default. claimToken is
# the one Plex-specific settings key: see
# docs/superpowers/specs/2026-08-20-phase-1-3-catalog-apps-design.md's
# "Plex Claim-Token Mechanism" for why this can't be a real declarative
# NixOS module option (Plex's claim tokens can only be generated by an
# authenticated plex.tv session, by design).
{
  id = "plex";
  displayName = "Plex";
  category = "media-server";
  summary = "Media server for streaming movies, TV, and music.";

  defaultPort = 32400;
  defaultSubdomain = "plex";
  defaultMediaAccess = "read";
  defaultAuthPolicy = "one_factor";

  # Plex's native apps (smart TVs, game consoles, mobile) cannot follow a
  # forward-auth redirect -- /identity is Plex's own documented
  # unauthenticated endpoint used by clients for server discovery.
  authBypassPaths = [ "/identity" ];

  healthCheck = {
    path = "/identity";
    expectStatus = 200;
    timeoutSec = 30;
  };

  integrations = {
    providesTo = [ ];
    consumes = [ ];
  };

  settingsSchema = {
    type = "object";
    additionalProperties = false;
    properties.claimToken = {
      type = "string";
      default = "";
    };
  };

  docsUrl = "https://support.plex.tv/";
  iconSlug = "plex";
}
