# Catalog metadata for Plex. Like Jellyfin, no port option in the NixOS
# module -- defaultPort documents Plex's own fixed default. claimToken is
# the one Plex-specific settings key: see
# docs/superpowers/specs/2026-08-20-phase-1-3-catalog-apps-design.md's
# "Plex Claim-Token Mechanism" for why this can't be a real declarative
# NixOS module option (Plex's claim tokens can only be generated by an
# authenticated plex.tv session, by design).
{
  id = "plex";
  displayName = "Plex";
  category = "media-server";
  summary = "Media server for streaming movies, TV, and music.";

  defaultPort = 32400;
  defaultSubdomain = "plex";
  defaultMediaAccess = "read";
  # "bypass", not one_factor, and this is a correctness matter rather than
  # a convenience one. Plex's native clients (Roku, Apple TV, game consoles, mobile)
  # authenticate with Plex's own token and have no browser to
  # complete an Authelia redirect with -- forward-auth in front of them does
  # not prompt for a login, it makes every native client fail to connect,
  # while a desktop browser still works. That asymmetry is what makes it
  # easy to misdiagnose.
  #
  # This app is NOT thereby unauthenticated: it ships its own login, which
  # is why crates/ferrum-install/src/sso.rs lists it in APPS_WITH_OWN_LOGIN
  # and does not count it among the apps left open when Authelia is off.
  # Keep those two facts in step.
  #
  # authBypassPaths below stays as documentation of the endpoints clients
  # hit before authenticating; with a bypass policy the whole vhost is
  # already unguarded, so it has no additional effect here.
  defaultAuthPolicy = "bypass";

  # nixpkgs' plexmediaserver package is licensed unfree; without allowing
  # it, the whole host config fails to evaluate the moment this app is
  # enabled. Collected centrally across the whole catalog by
  # modules/core/overlays.nix -- see that file's comment for why this
  # can't be set per-app inside service.nix (it doesn't compose with a
  # second unfree app's own predicate).
  unfreePackages = [ "plexmediaserver" ];

  # Plex's native apps (smart TVs, game consoles, mobile) cannot follow a
  # forward-auth redirect -- /identity is Plex's own documented
  # unauthenticated endpoint used by clients for server discovery.
  authBypassPaths = [ "/identity" ];

  healthCheck = {
    path = "/identity";
    expectStatus = 200;
    timeoutSec = 30;
  };

  integrations = {
    providesTo = [ ];
    consumes = [ ];
  };

  settingsSchema = {
    type = "object";
    additionalProperties = false;
    properties.claimToken = {
      type = "string";
      default = "";
    };
  };

  docsUrl = "https://support.plex.tv/";
  iconSlug = "plex";
}
