# Prowlarr, wired through the uniform ferrum.apps.prowlarr submodule onto
# nixpkgs' services.prowlarr. Unlike Sonarr/Radarr, the upstream module
# uses DynamicUser -- there is no persistent "prowlarr" user, so (correctly,
# since mediaAccess defaults to "none" for this app) there is no media-group
# wiring here, and the sops secret's `owner` is left at sops-nix's own
# default (root) rather than "prowlarr" -- systemd reads EnvironmentFile=
# as root before the service's dynamic user is even created, so there is
# no "prowlarr" user for the secret file to be owned by at the point it's
# read. environmentFiles points at sops-nix's decrypted API-key secret,
# generated by ferrum-apply's preflight step (see
# crates/ferrum-apply/src/secrets.rs) before every build -- same mechanism
# as Sonarr's, see that file's comment for why.
{ config, lib, ... }:
let
  ferrum = config.ferrum;
  app = ferrum.apps.prowlarr or { enable = false; };
  proxyLib = import ../../proxy/lib.nix { inherit lib; };
in
lib.mkIf app.enable {
  sops.secrets."prowlarr-apikey" = {
    # See modules/apps/sonarr/service.nix's comment on this exact line --
    # `/. + "string"`, not plain string interpolation, is what satisfies
    # sops.validateSopsFiles' isPath-or-store-prefixed-string assertion
    # while keeping ferrum.secretsDir configurable.
    sopsFile = /. + "${ferrum.secretsDir}/prowlarr-apikey.sops";
    format = "binary";
    # See modules/apps/sonarr/service.nix's comment on this exact line --
    # without restartUnits, rotating this key would leave prowlarr.service
    # running with the old one until something else restarts it.
    restartUnits = [ "prowlarr.service" ];
  };

  services.prowlarr = {
    enable = true;
    dataDir = app.stateDir;
    environmentFiles = [ config.sops.secrets."prowlarr-apikey".path ];
    settings = {
      server = {
        port = app.port;
        bindaddress = "127.0.0.1";
      };
      # Disables Prowlarr's own login page entirely -- Authelia's
      # forward-auth (modules/proxy/nginx.nix's auth_request wiring)
      # is the only auth layer once ferrum.auth.enable is true, per
      # this plan's confirmed answer to "does the app keep native
      # login as defense-in-depth" (it doesn't -- one identity, one
      # login, matching the SSO model cleanly). Only applied when
      # ferrum.auth.enable is actually true, so an operator running
      # without Authelia still gets Prowlarr's own login as a fallback.
      auth = lib.mkIf (proxyLib.authGated ferrum app) {
        method = "External";
      };
      log.analyticsenabled = false;
      update.mechanism = "external";
    };
  };

  systemd.services.prowlarr = {
    wantedBy = lib.mkForce [ "ferrum-apps.target" ];
    partOf = [ "ferrum-apps.target" ];
    unitConfig.ConditionPathExists = "!/var/lib/ferrum/state-restore-failed";
    serviceConfig = lib.filterAttrs (_: v: v != null) {
      MemoryMax = app.resources.memoryMax;
      CPUQuota = app.resources.cpuQuota;
    };
  };
}
