# Prowlarr, wired through the uniform ferrum.apps.prowlarr submodule onto
# nixpkgs' services.prowlarr. Unlike Sonarr/Radarr, the upstream module
# uses DynamicUser -- there is no persistent "prowlarr" user, so (correctly,
# since mediaAccess defaults to "none" for this app) there is no media-group
# wiring here, and the sops secret's `owner` is left at sops-nix's own
# default (root) rather than "prowlarr" -- systemd reads EnvironmentFile=
# as root before the service's dynamic user is even created, so there is
# no "prowlarr" user for the secret file to be owned by at the point it's
# read. environmentFiles points at sops-nix's decrypted API-key secret,
# generated by ferrum-apply's preflight step (see
# crates/ferrum-apply/src/secrets.rs) before every build -- same mechanism
# as Sonarr's, see that file's comment for why.
{ config, lib, ... }:
let
  ferrum = config.ferrum;
  app = ferrum.apps.prowlarr or { enable = false; };
in
lib.mkIf app.enable {
  sops.secrets."prowlarr-apikey" = {
    sopsFile = "${ferrum.secretsDir}/prowlarr-apikey.sops";
    format = "binary";
  };

  services.prowlarr = {
    enable = true;
    dataDir = app.stateDir;
    environmentFiles = [ config.sops.secrets."prowlarr-apikey".path ];
    settings = {
      server = {
        port = app.port;
        bindaddress = "127.0.0.1";
      };
      log.analyticsenabled = false;
      update.mechanism = "external";
    };
  };

  systemd.services.prowlarr = {
    wantedBy = lib.mkForce [ "ferrum-apps.target" ];
    partOf = [ "ferrum-apps.target" ];
    unitConfig.ConditionPathExists = "!/var/lib/ferrum/state-restore-failed";
    serviceConfig = lib.filterAttrs (_: v: v != null) {
      MemoryMax = app.resources.memoryMax;
      CPUQuota = app.resources.cpuQuota;
    };
  };
}
