# Sonarr, wired through the uniform ferrum.apps.sonarr submodule onto
# nixpkgs' services.sonarr (part of the shared servarr framework -- see
# nixos/modules/services/misc/servarr/ upstream).
#
# services.sonarr.environmentFiles points at sops-nix's decrypted API-key
# secret, generated by ferrum-apply's preflight step (see
# crates/ferrum-apply/src/secrets.rs) before every build -- Sonarr never
# generates its own key, ferrum chooses it up front, which is what makes
# the reconciler's cross-app registration (Phase 1.4b) possible without
# scraping config.xml.
{ config, lib, ... }:
let
  ferrum = config.ferrum;
  app = ferrum.apps.sonarr or { enable = false; };
in
lib.mkIf app.enable {
  sops.secrets."sonarr-apikey" = {
    # `/. + "string"` (path-concatenation), NOT `"${ferrum.secretsDir}/..."`
    # (plain string interpolation) -- sops.validateSopsFiles (on by
    # default) asserts sopsFile is either a genuine Nix path VALUE
    # (builtins.isPath) or a string already prefixed with /nix/store; a
    # plain interpolated string satisfies neither, even though it looks
    # like a path and points at a real file (found for real during this
    # task's own verification: the string form built and evaluated fine
    # under Phase 1.3's eval-only validateSopsFiles=false example host,
    # but failed this exact assertion the moment a real host actually
    # validates its secrets). `/. + "str"` is confirmed via a real `nix
    # eval` to produce a value with builtins.isPath == true even though
    # ferrum.secretsDir is a runtime-configurable string, which is what
    # actually satisfies the assertion while keeping secretsDir
    # configurable.
    sopsFile = /. + "${ferrum.secretsDir}/sonarr-apikey.sops";
    format = "binary";
    owner = "sonarr";
    # sops-nix's decrypted-secret PATH (config.sops.secrets."sonarr-apikey".path,
    # used by environmentFiles below) is invariant under a content change --
    # regenerating this key (e.g. deleting the .sops file and re-applying)
    # decrypts new content to the same path, which switch-to-configuration
    # has no way to notice on its own. Without restartUnits, sonarr.service
    # would keep running with the OLD key loaded in memory until something
    # else restarts it. restartUnits is a real sops-nix option (works the
    # same way as systemd.services.<name>.restartTriggers, scoped
    # per-secret) -- same mechanism qBittorrent's VPN secret uses, see
    # modules/apps/qbittorrent/service.nix.
    restartUnits = [ "sonarr.service" ];
  };

  services.sonarr = {
    enable = true;
    dataDir = app.stateDir;
    user = "sonarr";
    group = "sonarr";
    openFirewall = false;
    environmentFiles = [ config.sops.secrets."sonarr-apikey".path ];
    settings = {
      server = {
        port = app.port;
        bindaddress = "127.0.0.1";
      } // lib.optionalAttrs (app.settings ? urlBase && app.settings.urlBase != "") {
        urlbase = app.settings.urlBase;
      };
      # Disables Sonarr's own login page entirely -- Authelia's
      # forward-auth (modules/proxy/nginx.nix's auth_request wiring)
      # is the only auth layer once ferrum.auth.enable is true, per
      # this plan's confirmed answer to "does the app keep native
      # login as defense-in-depth" (it doesn't -- one identity, one
      # login, matching the SSO model cleanly). Only applied when
      # ferrum.auth.enable is actually true, so an operator running
      # without Authelia still gets Sonarr's own login as a fallback.
      auth = lib.mkIf ferrum.auth.enable {
        method = "External";
      };
      log.analyticsenabled = false;
      update.mechanism = "external";
    };
  };

  users.users.sonarr.extraGroups =
    lib.optional (app.mediaAccess != "none") ferrum.storage.mediaGroup;

  systemd.services.sonarr = {
    # Pulled in by ferrum-apps.target instead of multi-user.target directly,
    # so `systemctl stop ferrum-apps.target` (what apply does before every
    # snapshot) actually controls it.
    wantedBy = lib.mkForce [ "ferrum-apps.target" ];
    partOf = [ "ferrum-apps.target" ];
    # Every app service must carry this condition itself, not just the
    # target -- verified against real systemd (tests/state-restore-interlock.nix):
    # WantedBy=/Wants= start-propagation from a target does NOT check the
    # target's own ConditionPathExists result, so putting the condition only
    # on ferrum-apps.target lets this unit start anyway when the target is
    # skipped. See modules/core/generations.nix for the full explanation.
    unitConfig.ConditionPathExists = "!/var/lib/ferrum/state-restore-failed";
    serviceConfig = lib.filterAttrs (_: v: v != null) {
      MemoryMax = app.resources.memoryMax;
      CPUQuota = app.resources.cpuQuota;
    };
  };
}
