# Sonarr, wired through the uniform ferrum.apps.sonarr submodule onto
# nixpkgs' services.sonarr (part of the shared servarr framework -- see
# nixos/modules/services/misc/servarr/ upstream).
#
# services.sonarr.environmentFiles points at sops-nix's decrypted API-key
# secret, generated by ferrum-apply's preflight step (see
# crates/ferrum-apply/src/secrets.rs) before every build -- Sonarr never
# generates its own key, ferrum chooses it up front, which is what makes
# the reconciler's cross-app registration (Phase 1.4b) possible without
# scraping config.xml.
{ config, lib, ... }:
let
  ferrum = config.ferrum;
  app = ferrum.apps.sonarr or { enable = false; };
in
lib.mkIf app.enable {
  sops.secrets."sonarr-apikey" = {
    sopsFile = "${ferrum.secretsDir}/sonarr-apikey.sops";
    format = "binary";
    owner = "sonarr";
  };

  services.sonarr = {
    enable = true;
    dataDir = app.stateDir;
    user = "sonarr";
    group = "sonarr";
    openFirewall = false;
    environmentFiles = [ config.sops.secrets."sonarr-apikey".path ];
    settings = {
      server = {
        port = app.port;
        bindaddress = "127.0.0.1";
      } // lib.optionalAttrs (app.settings ? urlBase && app.settings.urlBase != "") {
        urlbase = app.settings.urlBase;
      };
      log.analyticsenabled = false;
      update.mechanism = "external";
    };
  };

  users.users.sonarr.extraGroups =
    lib.optional (app.mediaAccess != "none") ferrum.storage.mediaGroup;

  systemd.services.sonarr = {
    # Pulled in by ferrum-apps.target instead of multi-user.target directly,
    # so `systemctl stop ferrum-apps.target` (what apply does before every
    # snapshot) actually controls it.
    wantedBy = lib.mkForce [ "ferrum-apps.target" ];
    partOf = [ "ferrum-apps.target" ];
    # Every app service must carry this condition itself, not just the
    # target -- verified against real systemd (tests/state-restore-interlock.nix):
    # WantedBy=/Wants= start-propagation from a target does NOT check the
    # target's own ConditionPathExists result, so putting the condition only
    # on ferrum-apps.target lets this unit start anyway when the target is
    # skipped. See modules/core/generations.nix for the full explanation.
    unitConfig.ConditionPathExists = "!/var/lib/ferrum/state-restore-failed";
    serviceConfig = lib.filterAttrs (_: v: v != null) {
      MemoryMax = app.resources.memoryMax;
      CPUQuota = app.resources.cpuQuota;
    };
  };
}
