# Radarr, wired through the uniform ferrum.apps.radarr submodule onto
# nixpkgs' services.radarr (shares Sonarr's servarr framework -- see
# nixos/modules/services/misc/servarr/). environmentFiles points at
# sops-nix's decrypted API-key secret, generated by ferrum-apply's
# preflight step (see crates/ferrum-apply/src/secrets.rs) before every
# build -- same mechanism as Sonarr's, see that file's comment for why.
{ config, lib, ... }:
let
  ferrum = config.ferrum;
  app = ferrum.apps.radarr or { enable = false; };
  proxyLib = import ../../proxy/lib.nix { inherit lib; };
in
lib.mkIf app.enable {
  sops.secrets."radarr-apikey" = {
    # See modules/apps/sonarr/service.nix's comment on this exact line --
    # `/. + "string"`, not plain string interpolation, is what satisfies
    # sops.validateSopsFiles' isPath-or-store-prefixed-string assertion
    # while keeping ferrum.secretsDir configurable.
    sopsFile = /. + "${ferrum.secretsDir}/radarr-apikey.sops";
    format = "binary";
    owner = "radarr";
    # See modules/apps/sonarr/service.nix's comment on this exact line --
    # without restartUnits, rotating this key would leave radarr.service
    # running with the old one until something else restarts it.
    restartUnits = [ "radarr.service" ];
  };

  services.radarr = {
    enable = true;
    dataDir = app.stateDir;
    user = "radarr";
    group = "radarr";
    environmentFiles = [ config.sops.secrets."radarr-apikey".path ];
    settings = {
      server = {
        port = app.port;
        bindaddress = "127.0.0.1";
      } // lib.optionalAttrs (app.settings ? urlBase && app.settings.urlBase != "") {
        urlbase = app.settings.urlBase;
      };
      # Disables Radarr's own login page entirely -- Authelia's
      # forward-auth (modules/proxy/nginx.nix's auth_request wiring)
      # is the only auth layer once ferrum.auth.enable is true, per
      # this plan's confirmed answer to "does the app keep native
      # login as defense-in-depth" (it doesn't -- one identity, one
      # login, matching the SSO model cleanly). Only applied when
      # ferrum.auth.enable is actually true, so an operator running
      # without Authelia still gets Radarr's own login as a fallback.
      auth = lib.mkIf (proxyLib.authGated ferrum app) {
        method = "External";
      };
      log.analyticsenabled = false;
      update.mechanism = "external";
    };
  };

  users.users.radarr.extraGroups =
    lib.optional (app.mediaAccess != "none") ferrum.storage.mediaGroup;

  systemd.services.radarr = {
    # Pulled in by ferrum-apps.target instead of multi-user.target directly,
    # so `systemctl stop ferrum-apps.target` (what apply does before every
    # snapshot) actually controls it, and the fail-closed interlock (every
    # app service must carry ConditionPathExists itself -- see
    # modules/core/generations.nix for why the target's own condition alone
    # doesn't gate dependents) applies.
    wantedBy = lib.mkForce [ "ferrum-apps.target" ];
    partOf = [ "ferrum-apps.target" ];
    unitConfig.ConditionPathExists = "!/var/lib/ferrum/state-restore-failed";
    serviceConfig = lib.filterAttrs (_: v: v != null) {
      MemoryMax = app.resources.memoryMax;
      CPUQuota = app.resources.cpuQuota;
    };
  };
}
